require 'tests/acceptance/basic_gameplay.rb'
require 'tests/lib/component.rb'
require 'tests/lib/cp437_spritesheet_tileset.rb'
require 'tests/lib/entity_store.rb'
require 'tests/lib/string_utf8_chars.rb'
